# Generated by Django 4.2.10 on 2024-03-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_tokens_alredy_have_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokens_alredy_have',
            table='Tokens_alredy_have',
        ),
    ]
