# Generated by Django 4.2.10 on 2024-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_tokens_alredy_have_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparteman_buy_details',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=20)),
                ('mahal_english', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Aparteman_buy_details',
            },
        ),
    ]
