# Generated by Django 4.2.10 on 2024-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_aparteman_buy_details_image_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='city_persian',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='mahal_persian',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
