# Generated by Django 4.2.10 on 2024-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_aparteman_buy_details_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparteman_buy_details',
            name='title',
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='meter',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
