# Generated by Django 4.2.10 on 2024-03-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_aparteman_buy_details_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='asansor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='kooler',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='parking',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='room',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='tabagheh',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
