# Generated by Django 4.2.10 on 2024-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_aparteman_buy_details_asansor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='desck',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='price_meter',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='price_total',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='aparteman_buy_details',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
